# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl-Critic-Storable
version:      0.01
version_from: lib/Perl/Critic/Storable.pm
installdirs:  site
requires:
    Perl::Critic:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
